ollama:
  # -- List of models to pull at container startup
  models: 
    - llama2


ingress:
  apiVersion: networking.k8s.io/v1
  metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ollama
  namespace: ollama
  enabled: true
  hosts:
  - host: ai.yohrannes.com
    paths:
      - path: /
        pathType: Prefix

